### ISSUE TITLE
[EPIC] Brand new MVVM-based project

### ISSUE THREAD

**Issue by sappho192** [sappho192/IronworksTranslator#60]
This will replace the current WPF project.

## To-do List (without attaching the game)
- [x] Create UI
- [x] Create i18n-based UI text (#53 )
- [x] Migrate UI and settings
- [x] Migrate App icon
- [x] Turn-on SingleFileApp feature on Publish mode
- [x] #30 
- [x] #47 
- [x] #2 
- [x] #68

## To-do List (attching to game is required)

- [x] Migrate FFXIV and translator-related stuff
- [x] Restore WatchDogMain feature
- [x] #9 
- [x] #16 
- [x] #21 
- [x] #34 
- [x] #39 
- [x] #42
- [x] #44 
- [x] #51
- [x] #56  
- [x] #57 
- [x] #64
- [x] #65
- [x] #66
- [x] #69 
- [x] #70
